(cl:in-package mcptam-msg)
(cl:export '(HEADER-VAL
          HEADER
          DFRAMEGRABDURATION-VAL
          DFRAMEGRABDURATION
          DFRAMEDELAYDURATION-VAL
          DFRAMEDELAYDURATION
          DTRACKINGDURATION-VAL
          DTRACKINGDURATION
          DFPS-VAL
          DFPS
          DGRABSUCCESSRATIO-VAL
          DGRABSUCCESSRATIO
          MESSAGE-VAL
          MESSAGE
))