(cl:in-package mcptam-msg)
(cl:export '(HEADER-VAL
          HEADER
          KF_DOWNSAMPLE-VAL
          KF_DOWNSAMPLE
          KF_MASK-VAL
          KF_MASK
          KF_FEATURE-VAL
          KF_FEATURE
          SBI-VAL
          SBI
          MOTION-VAL
          MOTION
          PVS-VAL
          PVS
          SHUFFLE-VAL
          SHUFFLE
          COARSE-VAL
          COARSE
          FINE-VAL
          FINE
          POSE-VAL
          POSE
          DEPTH-VAL
          DEPTH
          ADD-VAL
          ADD
          TOTAL-VAL
          TOTAL
          MAP_NUM_MKFS-VAL
          MAP_NUM_MKFS
          MAP_NUM_POINTS-VAL
          MAP_NUM_POINTS
))