// Generated by gencpp from file mcptam/MapMakerTiming.msg
// DO NOT EDIT!


#ifndef MCPTAM_MESSAGE_MAPMAKERTIMING_H
#define MCPTAM_MESSAGE_MAPMAKERTIMING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mcptam
{
template <class ContainerAllocator>
struct MapMakerTiming_
{
  typedef MapMakerTiming_<ContainerAllocator> Type;

  MapMakerTiming_()
    : header()
    , elapsed(0.0)
    , accepted(0)
    , total(0)
    , map_num_mkfs(0)
    , map_num_points(0)  {
    }
  MapMakerTiming_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , elapsed(0.0)
    , accepted(0)
    , total(0)
    , map_num_mkfs(0)
    , map_num_points(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _elapsed_type;
  _elapsed_type elapsed;

   typedef int32_t _accepted_type;
  _accepted_type accepted;

   typedef int32_t _total_type;
  _total_type total;

   typedef int32_t _map_num_mkfs_type;
  _map_num_mkfs_type map_num_mkfs;

   typedef int32_t _map_num_points_type;
  _map_num_points_type map_num_points;




  typedef boost::shared_ptr< ::mcptam::MapMakerTiming_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcptam::MapMakerTiming_<ContainerAllocator> const> ConstPtr;

}; // struct MapMakerTiming_

typedef ::mcptam::MapMakerTiming_<std::allocator<void> > MapMakerTiming;

typedef boost::shared_ptr< ::mcptam::MapMakerTiming > MapMakerTimingPtr;
typedef boost::shared_ptr< ::mcptam::MapMakerTiming const> MapMakerTimingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcptam::MapMakerTiming_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcptam::MapMakerTiming_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mcptam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'mcptam': ['/home/vgrlab/catkin_ws/src/mcptam/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::MapMakerTiming_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::MapMakerTiming_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::MapMakerTiming_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::MapMakerTiming_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::MapMakerTiming_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::MapMakerTiming_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcptam::MapMakerTiming_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80db30380a7157a873d7db983881ec5a";
  }

  static const char* value(const ::mcptam::MapMakerTiming_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80db30380a7157a8ULL;
  static const uint64_t static_value2 = 0x73d7db983881ec5aULL;
};

template<class ContainerAllocator>
struct DataType< ::mcptam::MapMakerTiming_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcptam/MapMakerTiming";
  }

  static const char* value(const ::mcptam::MapMakerTiming_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcptam::MapMakerTiming_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 elapsed\n\
int32 accepted\n\
int32 total\n\
int32 map_num_mkfs\n\
int32 map_num_points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::mcptam::MapMakerTiming_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcptam::MapMakerTiming_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.elapsed);
      stream.next(m.accepted);
      stream.next(m.total);
      stream.next(m.map_num_mkfs);
      stream.next(m.map_num_points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapMakerTiming_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcptam::MapMakerTiming_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcptam::MapMakerTiming_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "elapsed: ";
    Printer<float>::stream(s, indent + "  ", v.elapsed);
    s << indent << "accepted: ";
    Printer<int32_t>::stream(s, indent + "  ", v.accepted);
    s << indent << "total: ";
    Printer<int32_t>::stream(s, indent + "  ", v.total);
    s << indent << "map_num_mkfs: ";
    Printer<int32_t>::stream(s, indent + "  ", v.map_num_mkfs);
    s << indent << "map_num_points: ";
    Printer<int32_t>::stream(s, indent + "  ", v.map_num_points);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCPTAM_MESSAGE_MAPMAKERTIMING_H
