// Generated by gencpp from file mcptam/ModifyMap.msg
// DO NOT EDIT!


#ifndef MCPTAM_MESSAGE_MODIFYMAP_H
#define MCPTAM_MESSAGE_MODIFYMAP_H

#include <ros/service_traits.h>


#include <mcptam/ModifyMapRequest.h>
#include <mcptam/ModifyMapResponse.h>


namespace mcptam
{

struct ModifyMap
{

typedef ModifyMapRequest Request;
typedef ModifyMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModifyMap
} // namespace mcptam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mcptam::ModifyMap > {
  static const char* value()
  {
    return "fa7bdbefce6df3cb1fff6a1c781fb2bc";
  }

  static const char* value(const ::mcptam::ModifyMap&) { return value(); }
};

template<>
struct DataType< ::mcptam::ModifyMap > {
  static const char* value()
  {
    return "mcptam/ModifyMap";
  }

  static const char* value(const ::mcptam::ModifyMap&) { return value(); }
};


// service_traits::MD5Sum< ::mcptam::ModifyMapRequest> should match 
// service_traits::MD5Sum< ::mcptam::ModifyMap > 
template<>
struct MD5Sum< ::mcptam::ModifyMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mcptam::ModifyMap >::value();
  }
  static const char* value(const ::mcptam::ModifyMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcptam::ModifyMapRequest> should match 
// service_traits::DataType< ::mcptam::ModifyMap > 
template<>
struct DataType< ::mcptam::ModifyMapRequest>
{
  static const char* value()
  {
    return DataType< ::mcptam::ModifyMap >::value();
  }
  static const char* value(const ::mcptam::ModifyMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mcptam::ModifyMapResponse> should match 
// service_traits::MD5Sum< ::mcptam::ModifyMap > 
template<>
struct MD5Sum< ::mcptam::ModifyMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mcptam::ModifyMap >::value();
  }
  static const char* value(const ::mcptam::ModifyMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcptam::ModifyMapResponse> should match 
// service_traits::DataType< ::mcptam::ModifyMap > 
template<>
struct DataType< ::mcptam::ModifyMapResponse>
{
  static const char* value()
  {
    return DataType< ::mcptam::ModifyMap >::value();
  }
  static const char* value(const ::mcptam::ModifyMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MCPTAM_MESSAGE_MODIFYMAP_H
