// Generated by gencpp from file mcptam/NetworkMeasurement.msg
// DO NOT EDIT!


#ifndef MCPTAM_MESSAGE_NETWORKMEASUREMENT_H
#define MCPTAM_MESSAGE_NETWORKMEASUREMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mcptam
{
template <class ContainerAllocator>
struct NetworkMeasurement_
{
  typedef NetworkMeasurement_<ContainerAllocator> Type;

  NetworkMeasurement_()
    : nLevel(0)
    , bSubPix(false)
    , v2RootPos()
    , eSource(0)
    , mapPointId()  {
      v2RootPos.assign(0.0);
  }
  NetworkMeasurement_(const ContainerAllocator& _alloc)
    : nLevel(0)
    , bSubPix(false)
    , v2RootPos()
    , eSource(0)
    , mapPointId(_alloc)  {
  (void)_alloc;
      v2RootPos.assign(0.0);
  }



   typedef uint8_t _nLevel_type;
  _nLevel_type nLevel;

   typedef uint8_t _bSubPix_type;
  _bSubPix_type bSubPix;

   typedef boost::array<double, 2>  _v2RootPos_type;
  _v2RootPos_type v2RootPos;

   typedef uint8_t _eSource_type;
  _eSource_type eSource;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mapPointId_type;
  _mapPointId_type mapPointId;




  typedef boost::shared_ptr< ::mcptam::NetworkMeasurement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcptam::NetworkMeasurement_<ContainerAllocator> const> ConstPtr;

}; // struct NetworkMeasurement_

typedef ::mcptam::NetworkMeasurement_<std::allocator<void> > NetworkMeasurement;

typedef boost::shared_ptr< ::mcptam::NetworkMeasurement > NetworkMeasurementPtr;
typedef boost::shared_ptr< ::mcptam::NetworkMeasurement const> NetworkMeasurementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcptam::NetworkMeasurement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcptam::NetworkMeasurement_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mcptam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mcptam': ['/home/vgrlab/catkin_ws/src/mcptam/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::NetworkMeasurement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::NetworkMeasurement_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::NetworkMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::NetworkMeasurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::NetworkMeasurement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::NetworkMeasurement_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcptam::NetworkMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6beed70fe5b9a4435fd44bc9deb3fa1";
  }

  static const char* value(const ::mcptam::NetworkMeasurement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6beed70fe5b9a44ULL;
  static const uint64_t static_value2 = 0x35fd44bc9deb3fa1ULL;
};

template<class ContainerAllocator>
struct DataType< ::mcptam::NetworkMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcptam/NetworkMeasurement";
  }

  static const char* value(const ::mcptam::NetworkMeasurement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcptam::NetworkMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 nLevel\n\
bool bSubPix\n\
float64[2] v2RootPos\n\
uint8 eSource\n\
string mapPointId\n\
";
  }

  static const char* value(const ::mcptam::NetworkMeasurement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcptam::NetworkMeasurement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nLevel);
      stream.next(m.bSubPix);
      stream.next(m.v2RootPos);
      stream.next(m.eSource);
      stream.next(m.mapPointId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NetworkMeasurement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcptam::NetworkMeasurement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcptam::NetworkMeasurement_<ContainerAllocator>& v)
  {
    s << indent << "nLevel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nLevel);
    s << indent << "bSubPix: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bSubPix);
    s << indent << "v2RootPos[]" << std::endl;
    for (size_t i = 0; i < v.v2RootPos.size(); ++i)
    {
      s << indent << "  v2RootPos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.v2RootPos[i]);
    }
    s << indent << "eSource: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.eSource);
    s << indent << "mapPointId: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mapPointId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCPTAM_MESSAGE_NETWORKMEASUREMENT_H
