// Generated by gencpp from file mcptam/NetworkKeyFrame.msg
// DO NOT EDIT!


#ifndef MCPTAM_MESSAGE_NETWORKKEYFRAME_H
#define MCPTAM_MESSAGE_NETWORKKEYFRAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <mcptam/NetworkMeasurement.h>

namespace mcptam
{
template <class ContainerAllocator>
struct NetworkKeyFrame_
{
  typedef NetworkKeyFrame_<ContainerAllocator> Type;

  NetworkKeyFrame_()
    : mse3CamFromBase()
    , mse3CamFromWorld()
    , image()
    , mask()
    , mvMeasurements()
    , mdSceneDepthMean(0.0)
    , mdSceneDepthSigma(0.0)
    , mCamName()
    , mParentId()  {
    }
  NetworkKeyFrame_(const ContainerAllocator& _alloc)
    : mse3CamFromBase(_alloc)
    , mse3CamFromWorld(_alloc)
    , image(_alloc)
    , mask(_alloc)
    , mvMeasurements(_alloc)
    , mdSceneDepthMean(0.0)
    , mdSceneDepthSigma(0.0)
    , mCamName(_alloc)
    , mParentId(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mse3CamFromBase_type;
  _mse3CamFromBase_type mse3CamFromBase;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mse3CamFromWorld_type;
  _mse3CamFromWorld_type mse3CamFromWorld;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _mask_type;
  _mask_type mask;

   typedef std::vector< ::mcptam::NetworkMeasurement_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mcptam::NetworkMeasurement_<ContainerAllocator> >::other >  _mvMeasurements_type;
  _mvMeasurements_type mvMeasurements;

   typedef double _mdSceneDepthMean_type;
  _mdSceneDepthMean_type mdSceneDepthMean;

   typedef double _mdSceneDepthSigma_type;
  _mdSceneDepthSigma_type mdSceneDepthSigma;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mCamName_type;
  _mCamName_type mCamName;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mParentId_type;
  _mParentId_type mParentId;




  typedef boost::shared_ptr< ::mcptam::NetworkKeyFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcptam::NetworkKeyFrame_<ContainerAllocator> const> ConstPtr;

}; // struct NetworkKeyFrame_

typedef ::mcptam::NetworkKeyFrame_<std::allocator<void> > NetworkKeyFrame;

typedef boost::shared_ptr< ::mcptam::NetworkKeyFrame > NetworkKeyFramePtr;
typedef boost::shared_ptr< ::mcptam::NetworkKeyFrame const> NetworkKeyFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcptam::NetworkKeyFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcptam::NetworkKeyFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mcptam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mcptam': ['/home/vgrlab/catkin_ws/src/mcptam/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::NetworkKeyFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::NetworkKeyFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::NetworkKeyFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::NetworkKeyFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::NetworkKeyFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::NetworkKeyFrame_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcptam::NetworkKeyFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f59eaa4c697752d3cb2282e3985e3d4";
  }

  static const char* value(const ::mcptam::NetworkKeyFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f59eaa4c697752dULL;
  static const uint64_t static_value2 = 0x3cb2282e3985e3d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::mcptam::NetworkKeyFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcptam/NetworkKeyFrame";
  }

  static const char* value(const ::mcptam::NetworkKeyFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcptam::NetworkKeyFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mse3CamFromBase\n\
string mse3CamFromWorld\n\
sensor_msgs/Image image\n\
sensor_msgs/Image mask\n\
NetworkMeasurement[] mvMeasurements\n\
float64 mdSceneDepthMean\n\
float64 mdSceneDepthSigma\n\
string mCamName\n\
string mParentId\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: mcptam/NetworkMeasurement\n\
uint8 nLevel\n\
bool bSubPix\n\
float64[2] v2RootPos\n\
uint8 eSource\n\
string mapPointId\n\
";
  }

  static const char* value(const ::mcptam::NetworkKeyFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcptam::NetworkKeyFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mse3CamFromBase);
      stream.next(m.mse3CamFromWorld);
      stream.next(m.image);
      stream.next(m.mask);
      stream.next(m.mvMeasurements);
      stream.next(m.mdSceneDepthMean);
      stream.next(m.mdSceneDepthSigma);
      stream.next(m.mCamName);
      stream.next(m.mParentId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NetworkKeyFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcptam::NetworkKeyFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcptam::NetworkKeyFrame_<ContainerAllocator>& v)
  {
    s << indent << "mse3CamFromBase: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mse3CamFromBase);
    s << indent << "mse3CamFromWorld: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mse3CamFromWorld);
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "mask: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.mask);
    s << indent << "mvMeasurements[]" << std::endl;
    for (size_t i = 0; i < v.mvMeasurements.size(); ++i)
    {
      s << indent << "  mvMeasurements[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mcptam::NetworkMeasurement_<ContainerAllocator> >::stream(s, indent + "    ", v.mvMeasurements[i]);
    }
    s << indent << "mdSceneDepthMean: ";
    Printer<double>::stream(s, indent + "  ", v.mdSceneDepthMean);
    s << indent << "mdSceneDepthSigma: ";
    Printer<double>::stream(s, indent + "  ", v.mdSceneDepthSigma);
    s << indent << "mCamName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mCamName);
    s << indent << "mParentId: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mParentId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCPTAM_MESSAGE_NETWORKKEYFRAME_H
