// Generated by gencpp from file mcptam/NetworkMultiKeyFrame.msg
// DO NOT EDIT!


#ifndef MCPTAM_MESSAGE_NETWORKMULTIKEYFRAME_H
#define MCPTAM_MESSAGE_NETWORKMULTIKEYFRAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mcptam/NetworkKeyFrame.h>

namespace mcptam
{
template <class ContainerAllocator>
struct NetworkMultiKeyFrame_
{
  typedef NetworkMultiKeyFrame_<ContainerAllocator> Type;

  NetworkMultiKeyFrame_()
    : mse3BaseFromWorld()
    , mvKeyFrames()
    , mbFixed(false)
    , mdTotalDepthMean(0.0)
    , mId()  {
    }
  NetworkMultiKeyFrame_(const ContainerAllocator& _alloc)
    : mse3BaseFromWorld(_alloc)
    , mvKeyFrames(_alloc)
    , mbFixed(false)
    , mdTotalDepthMean(0.0)
    , mId(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mse3BaseFromWorld_type;
  _mse3BaseFromWorld_type mse3BaseFromWorld;

   typedef std::vector< ::mcptam::NetworkKeyFrame_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mcptam::NetworkKeyFrame_<ContainerAllocator> >::other >  _mvKeyFrames_type;
  _mvKeyFrames_type mvKeyFrames;

   typedef uint8_t _mbFixed_type;
  _mbFixed_type mbFixed;

   typedef double _mdTotalDepthMean_type;
  _mdTotalDepthMean_type mdTotalDepthMean;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mId_type;
  _mId_type mId;




  typedef boost::shared_ptr< ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator> const> ConstPtr;

}; // struct NetworkMultiKeyFrame_

typedef ::mcptam::NetworkMultiKeyFrame_<std::allocator<void> > NetworkMultiKeyFrame;

typedef boost::shared_ptr< ::mcptam::NetworkMultiKeyFrame > NetworkMultiKeyFramePtr;
typedef boost::shared_ptr< ::mcptam::NetworkMultiKeyFrame const> NetworkMultiKeyFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mcptam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mcptam': ['/home/vgrlab/catkin_ws/src/mcptam/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98b276a80a8dd282e5915f2a53818b19";
  }

  static const char* value(const ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98b276a80a8dd282ULL;
  static const uint64_t static_value2 = 0xe5915f2a53818b19ULL;
};

template<class ContainerAllocator>
struct DataType< ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcptam/NetworkMultiKeyFrame";
  }

  static const char* value(const ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mse3BaseFromWorld\n\
NetworkKeyFrame[] mvKeyFrames\n\
bool mbFixed\n\
float64 mdTotalDepthMean\n\
string mId\n\
\n\
================================================================================\n\
MSG: mcptam/NetworkKeyFrame\n\
string mse3CamFromBase\n\
string mse3CamFromWorld\n\
sensor_msgs/Image image\n\
sensor_msgs/Image mask\n\
NetworkMeasurement[] mvMeasurements\n\
float64 mdSceneDepthMean\n\
float64 mdSceneDepthSigma\n\
string mCamName\n\
string mParentId\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: mcptam/NetworkMeasurement\n\
uint8 nLevel\n\
bool bSubPix\n\
float64[2] v2RootPos\n\
uint8 eSource\n\
string mapPointId\n\
";
  }

  static const char* value(const ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mse3BaseFromWorld);
      stream.next(m.mvKeyFrames);
      stream.next(m.mbFixed);
      stream.next(m.mdTotalDepthMean);
      stream.next(m.mId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NetworkMultiKeyFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcptam::NetworkMultiKeyFrame_<ContainerAllocator>& v)
  {
    s << indent << "mse3BaseFromWorld: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mse3BaseFromWorld);
    s << indent << "mvKeyFrames[]" << std::endl;
    for (size_t i = 0; i < v.mvKeyFrames.size(); ++i)
    {
      s << indent << "  mvKeyFrames[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mcptam::NetworkKeyFrame_<ContainerAllocator> >::stream(s, indent + "    ", v.mvKeyFrames[i]);
    }
    s << indent << "mbFixed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mbFixed);
    s << indent << "mdTotalDepthMean: ";
    Printer<double>::stream(s, indent + "  ", v.mdTotalDepthMean);
    s << indent << "mId: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCPTAM_MESSAGE_NETWORKMULTIKEYFRAME_H
