// Generated by gencpp from file mcptam/SetDepthRequest.msg
// DO NOT EDIT!


#ifndef MCPTAM_MESSAGE_SETDEPTHREQUEST_H
#define MCPTAM_MESSAGE_SETDEPTHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>

namespace mcptam
{
template <class ContainerAllocator>
struct SetDepthRequest_
{
  typedef SetDepthRequest_<ContainerAllocator> Type;

  SetDepthRequest_()
    : depth()  {
    }
  SetDepthRequest_(const ContainerAllocator& _alloc)
    : depth(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _depth_type;
  _depth_type depth;




  typedef boost::shared_ptr< ::mcptam::SetDepthRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcptam::SetDepthRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetDepthRequest_

typedef ::mcptam::SetDepthRequest_<std::allocator<void> > SetDepthRequest;

typedef boost::shared_ptr< ::mcptam::SetDepthRequest > SetDepthRequestPtr;
typedef boost::shared_ptr< ::mcptam::SetDepthRequest const> SetDepthRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcptam::SetDepthRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcptam::SetDepthRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mcptam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'mcptam': ['/home/vgrlab/catkin_ws/src/mcptam/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::SetDepthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::SetDepthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::SetDepthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::SetDepthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::SetDepthRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::SetDepthRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcptam::SetDepthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f12ef97a66ad979156c91cd0a2739bb9";
  }

  static const char* value(const ::mcptam::SetDepthRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf12ef97a66ad9791ULL;
  static const uint64_t static_value2 = 0x56c91cd0a2739bb9ULL;
};

template<class ContainerAllocator>
struct DataType< ::mcptam::SetDepthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcptam/SetDepthRequest";
  }

  static const char* value(const ::mcptam::SetDepthRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcptam::SetDepthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32 depth\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::mcptam::SetDepthRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcptam::SetDepthRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDepthRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcptam::SetDepthRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcptam::SetDepthRequest_<ContainerAllocator>& v)
  {
    s << indent << "depth: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCPTAM_MESSAGE_SETDEPTHREQUEST_H
