// Generated by gencpp from file mcptam/SetDepth.msg
// DO NOT EDIT!


#ifndef MCPTAM_MESSAGE_SETDEPTH_H
#define MCPTAM_MESSAGE_SETDEPTH_H

#include <ros/service_traits.h>


#include <mcptam/SetDepthRequest.h>
#include <mcptam/SetDepthResponse.h>


namespace mcptam
{

struct SetDepth
{

typedef SetDepthRequest Request;
typedef SetDepthResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDepth
} // namespace mcptam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mcptam::SetDepth > {
  static const char* value()
  {
    return "a162f47a2d8133c9b6199b2666e904ff";
  }

  static const char* value(const ::mcptam::SetDepth&) { return value(); }
};

template<>
struct DataType< ::mcptam::SetDepth > {
  static const char* value()
  {
    return "mcptam/SetDepth";
  }

  static const char* value(const ::mcptam::SetDepth&) { return value(); }
};


// service_traits::MD5Sum< ::mcptam::SetDepthRequest> should match 
// service_traits::MD5Sum< ::mcptam::SetDepth > 
template<>
struct MD5Sum< ::mcptam::SetDepthRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mcptam::SetDepth >::value();
  }
  static const char* value(const ::mcptam::SetDepthRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcptam::SetDepthRequest> should match 
// service_traits::DataType< ::mcptam::SetDepth > 
template<>
struct DataType< ::mcptam::SetDepthRequest>
{
  static const char* value()
  {
    return DataType< ::mcptam::SetDepth >::value();
  }
  static const char* value(const ::mcptam::SetDepthRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mcptam::SetDepthResponse> should match 
// service_traits::MD5Sum< ::mcptam::SetDepth > 
template<>
struct MD5Sum< ::mcptam::SetDepthResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mcptam::SetDepth >::value();
  }
  static const char* value(const ::mcptam::SetDepthResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcptam::SetDepthResponse> should match 
// service_traits::DataType< ::mcptam::SetDepth > 
template<>
struct DataType< ::mcptam::SetDepthResponse>
{
  static const char* value()
  {
    return DataType< ::mcptam::SetDepth >::value();
  }
  static const char* value(const ::mcptam::SetDepthResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MCPTAM_MESSAGE_SETDEPTH_H
