// Generated by gencpp from file mcptam/Triple.msg
// DO NOT EDIT!


#ifndef MCPTAM_MESSAGE_TRIPLE_H
#define MCPTAM_MESSAGE_TRIPLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace mcptam
{
template <class ContainerAllocator>
struct Triple_
{
  typedef Triple_<ContainerAllocator> Type;

  Triple_()
    : p1()
    , p4()
    , p2()  {
    }
  Triple_(const ContainerAllocator& _alloc)
    : p1(_alloc)
    , p4(_alloc)
    , p2(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _p1_type;
  _p1_type p1;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _p4_type;
  _p4_type p4;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _p2_type;
  _p2_type p2;




  typedef boost::shared_ptr< ::mcptam::Triple_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcptam::Triple_<ContainerAllocator> const> ConstPtr;

}; // struct Triple_

typedef ::mcptam::Triple_<std::allocator<void> > Triple;

typedef boost::shared_ptr< ::mcptam::Triple > TriplePtr;
typedef boost::shared_ptr< ::mcptam::Triple const> TripleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcptam::Triple_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcptam::Triple_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mcptam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'mcptam': ['/home/vgrlab/catkin_ws/src/mcptam/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::Triple_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::Triple_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::Triple_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::Triple_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::Triple_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::Triple_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcptam::Triple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71b770be97f3faa3d4d391bca9d0184f";
  }

  static const char* value(const ::mcptam::Triple_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71b770be97f3faa3ULL;
  static const uint64_t static_value2 = 0xd4d391bca9d0184fULL;
};

template<class ContainerAllocator>
struct DataType< ::mcptam::Triple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcptam/Triple";
  }

  static const char* value(const ::mcptam::Triple_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcptam::Triple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point p1\n\
geometry_msgs/Point p4\n\
geometry_msgs/Point p2\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::mcptam::Triple_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcptam::Triple_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p1);
      stream.next(m.p4);
      stream.next(m.p2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Triple_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcptam::Triple_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcptam::Triple_<ContainerAllocator>& v)
  {
    s << indent << "p1: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.p1);
    s << indent << "p4: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.p4);
    s << indent << "p2: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.p2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCPTAM_MESSAGE_TRIPLE_H
