(cl:defpackage mcptam-msg
  (:use )
  (:export
   "<SYSTEMINFO>"
   "SYSTEMINFO"
   "<NETWORKOUTLIER>"
   "NETWORKOUTLIER"
   "<NETWORKKEYFRAME>"
   "NETWORKKEYFRAME"
   "<TRIPLE>"
   "TRIPLE"
   "<NETWORKMAPPOINT>"
   "NETWORKMAPPOINT"
   "<INTPOINTCLOUD>"
   "INTPOINTCLOUD"
   "<MAPMAKERTIMING>"
   "MAPMAKERTIMING"
   "<NETWORKMULTIKEYFRAME>"
   "NETWORKMULTIKEYFRAME"
   "<NETWORKMEASUREMENT>"
   "NETWORKMEASUREMENT"
   "<MAPINFO>"
   "MAPINFO"
   "<TRACKERSTATE>"
   "TRACKERSTATE"
   "<TRACKERTIMING>"
   "TRACKERTIMING"
  ))

