// Generated by gencpp from file mcptam/intPointCloud.msg
// DO NOT EDIT!


#ifndef MCPTAM_MESSAGE_INTPOINTCLOUD_H
#define MCPTAM_MESSAGE_INTPOINTCLOUD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mcptam
{
template <class ContainerAllocator>
struct intPointCloud_
{
  typedef intPointCloud_<ContainerAllocator> Type;

  intPointCloud_()
    : x(0)
    , y(0)
    , z(0)
    , rgb(0)  {
    }
  intPointCloud_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , z(0)
    , rgb(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _z_type;
  _z_type z;

   typedef int32_t _rgb_type;
  _rgb_type rgb;




  typedef boost::shared_ptr< ::mcptam::intPointCloud_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcptam::intPointCloud_<ContainerAllocator> const> ConstPtr;

}; // struct intPointCloud_

typedef ::mcptam::intPointCloud_<std::allocator<void> > intPointCloud;

typedef boost::shared_ptr< ::mcptam::intPointCloud > intPointCloudPtr;
typedef boost::shared_ptr< ::mcptam::intPointCloud const> intPointCloudConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcptam::intPointCloud_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcptam::intPointCloud_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mcptam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'mcptam': ['/home/vgrlab/catkin_ws/src/mcptam/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::intPointCloud_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::intPointCloud_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::intPointCloud_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::intPointCloud_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::intPointCloud_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::intPointCloud_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcptam::intPointCloud_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e8aa7ca3f6e6556533e883b3b820ff0";
  }

  static const char* value(const ::mcptam::intPointCloud_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e8aa7ca3f6e6556ULL;
  static const uint64_t static_value2 = 0x533e883b3b820ff0ULL;
};

template<class ContainerAllocator>
struct DataType< ::mcptam::intPointCloud_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcptam/intPointCloud";
  }

  static const char* value(const ::mcptam::intPointCloud_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcptam::intPointCloud_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
int32 z\n\
int32 rgb\n\
";
  }

  static const char* value(const ::mcptam::intPointCloud_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcptam::intPointCloud_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.rgb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct intPointCloud_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcptam::intPointCloud_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcptam::intPointCloud_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.z);
    s << indent << "rgb: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rgb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCPTAM_MESSAGE_INTPOINTCLOUD_H
