// Generated by gencpp from file mcptam/MapInfo.msg
// DO NOT EDIT!


#ifndef MCPTAM_MESSAGE_MAPINFO_H
#define MCPTAM_MESSAGE_MAPINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mcptam
{
template <class ContainerAllocator>
struct MapInfo_
{
  typedef MapInfo_<ContainerAllocator> Type;

  MapInfo_()
    : header()
    , nNumPoints(0)
    , nNumPointsInTrash(0)
    , nNumMultiKeyFrames(0)  {
    }
  MapInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , nNumPoints(0)
    , nNumPointsInTrash(0)
    , nNumMultiKeyFrames(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _nNumPoints_type;
  _nNumPoints_type nNumPoints;

   typedef uint32_t _nNumPointsInTrash_type;
  _nNumPointsInTrash_type nNumPointsInTrash;

   typedef uint32_t _nNumMultiKeyFrames_type;
  _nNumMultiKeyFrames_type nNumMultiKeyFrames;




  typedef boost::shared_ptr< ::mcptam::MapInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcptam::MapInfo_<ContainerAllocator> const> ConstPtr;

}; // struct MapInfo_

typedef ::mcptam::MapInfo_<std::allocator<void> > MapInfo;

typedef boost::shared_ptr< ::mcptam::MapInfo > MapInfoPtr;
typedef boost::shared_ptr< ::mcptam::MapInfo const> MapInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcptam::MapInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcptam::MapInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mcptam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'mcptam': ['/home/vgrlab/catkin_ws/src/mcptam/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::MapInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::MapInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::MapInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::MapInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::MapInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::MapInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcptam::MapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e32dd0a28046dc1a3d0b3366f3ecf30e";
  }

  static const char* value(const ::mcptam::MapInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe32dd0a28046dc1aULL;
  static const uint64_t static_value2 = 0x3d0b3366f3ecf30eULL;
};

template<class ContainerAllocator>
struct DataType< ::mcptam::MapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcptam/MapInfo";
  }

  static const char* value(const ::mcptam::MapInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcptam::MapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32 nNumPoints\n\
uint32 nNumPointsInTrash\n\
uint32 nNumMultiKeyFrames\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::mcptam::MapInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcptam::MapInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.nNumPoints);
      stream.next(m.nNumPointsInTrash);
      stream.next(m.nNumMultiKeyFrames);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcptam::MapInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcptam::MapInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "nNumPoints: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nNumPoints);
    s << indent << "nNumPointsInTrash: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nNumPointsInTrash);
    s << indent << "nNumMultiKeyFrames: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nNumMultiKeyFrames);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCPTAM_MESSAGE_MAPINFO_H
