// Generated by gencpp from file mcptam/ResetRequest.msg
// DO NOT EDIT!


#ifndef MCPTAM_MESSAGE_RESETREQUEST_H
#define MCPTAM_MESSAGE_RESETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mcptam
{
template <class ContainerAllocator>
struct ResetRequest_
{
  typedef ResetRequest_<ContainerAllocator> Type;

  ResetRequest_()
    : bReInit(false)
    , bSavePose(false)  {
    }
  ResetRequest_(const ContainerAllocator& _alloc)
    : bReInit(false)
    , bSavePose(false)  {
  (void)_alloc;
    }



   typedef uint8_t _bReInit_type;
  _bReInit_type bReInit;

   typedef uint8_t _bSavePose_type;
  _bSavePose_type bSavePose;




  typedef boost::shared_ptr< ::mcptam::ResetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcptam::ResetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetRequest_

typedef ::mcptam::ResetRequest_<std::allocator<void> > ResetRequest;

typedef boost::shared_ptr< ::mcptam::ResetRequest > ResetRequestPtr;
typedef boost::shared_ptr< ::mcptam::ResetRequest const> ResetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcptam::ResetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcptam::ResetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mcptam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'mcptam': ['/home/vgrlab/catkin_ws/src/mcptam/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::ResetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcptam::ResetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::ResetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcptam::ResetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::ResetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcptam::ResetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcptam::ResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d85de56296abae3d06c243bd44e6cdd";
  }

  static const char* value(const ::mcptam::ResetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d85de56296abae3ULL;
  static const uint64_t static_value2 = 0xd06c243bd44e6cddULL;
};

template<class ContainerAllocator>
struct DataType< ::mcptam::ResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcptam/ResetRequest";
  }

  static const char* value(const ::mcptam::ResetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcptam::ResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool bReInit\n\
bool bSavePose\n\
";
  }

  static const char* value(const ::mcptam::ResetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcptam::ResetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bReInit);
      stream.next(m.bSavePose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcptam::ResetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcptam::ResetRequest_<ContainerAllocator>& v)
  {
    s << indent << "bReInit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bReInit);
    s << indent << "bSavePose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bSavePose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCPTAM_MESSAGE_RESETREQUEST_H
