// Generated by gencpp from file mcptam/Reset.msg
// DO NOT EDIT!


#ifndef MCPTAM_MESSAGE_RESET_H
#define MCPTAM_MESSAGE_RESET_H

#include <ros/service_traits.h>


#include <mcptam/ResetRequest.h>
#include <mcptam/ResetResponse.h>


namespace mcptam
{

struct Reset
{

typedef ResetRequest Request;
typedef ResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reset
} // namespace mcptam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mcptam::Reset > {
  static const char* value()
  {
    return "9d85de56296abae3d06c243bd44e6cdd";
  }

  static const char* value(const ::mcptam::Reset&) { return value(); }
};

template<>
struct DataType< ::mcptam::Reset > {
  static const char* value()
  {
    return "mcptam/Reset";
  }

  static const char* value(const ::mcptam::Reset&) { return value(); }
};


// service_traits::MD5Sum< ::mcptam::ResetRequest> should match 
// service_traits::MD5Sum< ::mcptam::Reset > 
template<>
struct MD5Sum< ::mcptam::ResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mcptam::Reset >::value();
  }
  static const char* value(const ::mcptam::ResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcptam::ResetRequest> should match 
// service_traits::DataType< ::mcptam::Reset > 
template<>
struct DataType< ::mcptam::ResetRequest>
{
  static const char* value()
  {
    return DataType< ::mcptam::Reset >::value();
  }
  static const char* value(const ::mcptam::ResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mcptam::ResetResponse> should match 
// service_traits::MD5Sum< ::mcptam::Reset > 
template<>
struct MD5Sum< ::mcptam::ResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mcptam::Reset >::value();
  }
  static const char* value(const ::mcptam::ResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcptam::ResetResponse> should match 
// service_traits::DataType< ::mcptam::Reset > 
template<>
struct DataType< ::mcptam::ResetResponse>
{
  static const char* value()
  {
    return DataType< ::mcptam::Reset >::value();
  }
  static const char* value(const ::mcptam::ResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MCPTAM_MESSAGE_RESET_H
