(cl:defpackage mcptam-srv
  (:use )
  (:export
   "SETDEPTH"
   "<SETDEPTH-REQUEST>"
   "SETDEPTH-REQUEST"
   "<SETDEPTH-RESPONSE>"
   "SETDEPTH-RESPONSE"
   "FILTERPC"
   "<FILTERPC-REQUEST>"
   "FILTERPC-REQUEST"
   "<FILTERPC-RESPONSE>"
   "FILTERPC-RESPONSE"
   "MODIFYMAP"
   "<MODIFYMAP-REQUEST>"
   "MODIFYMAP-REQUEST"
   "<MODIFYMAP-RESPONSE>"
   "MODIFYMAP-RESPONSE"
   "RESET"
   "<RESET-REQUEST>"
   "RESET-REQUEST"
   "<RESET-RESPONSE>"
   "RESET-RESPONSE"
  ))

