set(_CATKIN_CURRENT_PACKAGE "mcptam")
set(mcptam_VERSION "0.1.2")
set(mcptam_MAINTAINER "Adam Harmat <adam.harmat@mail.mcgill.ca>")
set(mcptam_PACKAGE_FORMAT "1")
set(mcptam_BUILD_DEPENDS "roscpp" "image_transport" "sensor_msgs" "cv_bridge" "geometry_msgs" "tf" "message_filters" "std_msgs" "std_srvs" "visualization_msgs" "dynamic_reconfigure" "pcl_ros" "message_generation" "libg2o" "roslint")
set(mcptam_BUILD_EXPORT_DEPENDS "roscpp" "image_transport" "sensor_msgs" "cv_bridge" "geometry_msgs" "tf" "message_filters" "std_msgs" "std_srvs" "visualization_msgs" "dynamic_reconfigure" "pcl_ros" "message_runtime" "libg2o")
set(mcptam_BUILDTOOL_DEPENDS "catkin")
set(mcptam_BUILDTOOL_EXPORT_DEPENDS )
set(mcptam_EXEC_DEPENDS "roscpp" "image_transport" "sensor_msgs" "cv_bridge" "geometry_msgs" "tf" "message_filters" "std_msgs" "std_srvs" "visualization_msgs" "dynamic_reconfigure" "pcl_ros" "message_runtime" "libg2o")
set(mcptam_RUN_DEPENDS "roscpp" "image_transport" "sensor_msgs" "cv_bridge" "geometry_msgs" "tf" "message_filters" "std_msgs" "std_srvs" "visualization_msgs" "dynamic_reconfigure" "pcl_ros" "message_runtime" "libg2o")
set(mcptam_TEST_DEPENDS )
set(mcptam_DOC_DEPENDS )
set(mcptam_DEPRECATED "")